service: api

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  hangarService:
    handler: server.handler   # Este es el archivo que Lambda invoca
    events:
      - http:
          path: api/hangar   # Ruta para el servicio de hangares
          method: any                   # Permite cualquier método (POST, GET, etc.)
          cors: true

  userService:
    handler: server.handler   # Este es el archivo que Lambda invoca
    events:
      - http:
          path: api/users   # Ruta para el servicio de hangares
          method: any                   # Permite cualquier método (POST, GET, etc.)
          cors: true

  loginService:
    handler: server.handler   # Este es el archivo que Lambda invoca
    events:
      - http:
          path: api/login   # Ruta para el servicio de hangares
          method: any                   # Permite cualquier método (POST, GET, etc.)
          cors: true

plugins:
  - serverless-offline  # Permite ejecutar el servicio localmente
