service: api

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  hangarService:
    handler: server.handler
    events:
      - http:
          path: api/hangar
          method: any
          cors: true

  userService:
    handler: server.handler
    events:
      - http:
          path: api/users
          method: any
          cors: true

  loginService:
    handler: server.handler
    events:
      - http:
          path: api/token
          method: any
          cors: true

  swaggerDocService:
    handler: swagger.handler
    events:
      - http:
          path: api/docs
          method: get
          cors: true

plugins:
  - serverless-offline
